### ISSUE TITLE
多行注释的兼容性

### ISSUE THREAD

**Issue by fjqingyou** [DCTewi/Aegisub-Helper#8]
```
%[ template syl # comment @ 0
--[[
    测试
    多行
    注释
--]]
    test=0
%]
```

编译后的结果

Comment: 0,0:00:00.00,0:00:00.00,Default,comment,0,0,0,template syl,--[[测试多行注释test=0

**Comment by DCTewi** [comment]
> ```
> %[ template syl # comment @ 0
> --[[
>     测试
>     多行
>     注释
> --]]
>     test=0
> %]
> ```
> 
> 编译后的结果
> 
> Comment: 0,0:00:00.00,0:00:00.00,Default,comment,0,0,0,template syl,--[[测试多行注释test=0

多行注释使用的是`--[[`和`]]`
